# Day 07:    *Numpy: Numerical Python Library*
##  Numpy
- **NumPy** is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
- **Why Use NumPy?**

  - In Python we have lists that serve the purpose of arrays, but they are slow to process.
  - NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
  - The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
  - Arrays are very frequently used in data science, where speed and resources are very important.

###  Installation of NumPy
- If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
    - Install it using this command:
        - pip install numpy

###  Data Types in NumPy
- By default Python have these data types:
    - strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
    - integer - used to represent integer numbers. e.g. -1, -2, -3
    - float - used to represent real numbers. e.g. 1.2, 42.42
    - boolean - used to represent True or False.
    - complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
- Below is a list of all data types in NumPy and the characters used to represent them.

    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type ( void )


##  Array
- In computer science, an **array** data structure, or simply an array, is a data structure consisting of a collection of elements, each identified by at least one array index or key. An array is stored such that the position of each element can be computed from its index tuple by a mathematical formula.
- **NumPy arrays** facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.
- NumPy arrays are **faster** and **more compact** than Python lists. An array **consumes less memory** and is **convenient to use**.
###  Indexing in array
- **Indexing** is an operation that pulls out a select set of values from an array. The index of a value in an array is that value's location within the array. There is a difference between the value and where the value is stored in an array.
###  Creating an Array
- NumPy is used to work with arrays. The array object in NumPy is called **ndarray**.We can create a NumPy ndarray object by using the **array()** function.

In [1]:
import numpy as np
arr = np.array([45,78,67,546,67,8])
print(arr)
print(type(arr))

[ 45  78  67 546  67   8]
<class 'numpy.ndarray'>


- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [2]:
#Use a tuple to create a NumPy array:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


###  Dimensions in Arrays
- A **dimension** in arrays is one level of array depth (nested arrays).
- **nested array**: are arrays that have arrays as their elements.

####  Zero-D Arrays
- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [3]:
#Create a 0-D array with value 38
import numpy as np
arr = np.array(38)
print(arr)

38


####   One-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [4]:
#Create a 1-D array containing the values 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


####  Two-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.
- NumPy has a whole sub module dedicated towards matrix operations called **numpy.mat**

In [5]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


####  Three-D Arrays
- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
- These are often used to represent a 3rd order tensor.

In [6]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?
- NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


####   Higher Dimensional Arrays
- An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [8]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Numpy Practice Session
- Step 1: Install numpy in jupyter notebook
    - pip install numpy
- Step 2: Import Numpy Library as **np**

In [9]:
import numpy as np
food=np.array(["biryani", "raita", "coke"])
food

array(['biryani', 'raita', 'coke'], dtype='<U7')

In [10]:
price=np.array([120,20,30])
(price)

array([120,  20,  30])

In [11]:
#checking type for food
type(food)

numpy.ndarray

In [12]:
#checking type for price
type(price)

numpy.ndarray

In [13]:
#checking length of arrays food

len(food)

3

In [14]:
#checking length of arrays price
len(price)

3

In [15]:
# indexing of array price
price[1]

20

In [16]:
#indexing array food
food[0]

'biryani'

In [17]:
#finding mean in price
price.mean()

56.666666666666664

In [18]:
#zeros
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [19]:
#ones
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [20]:
#empty sets
c=np.empty(5)
c

array([1., 1., 1., 1., 1.])

In [21]:
#range
d= np.arange(5)
d

array([0, 1, 2, 3, 4])

In [22]:
#range from 5-10
e=np.arange(5,11)
e

array([ 5,  6,  7,  8,  9, 10])

In [23]:
#range with specific interval
f=np.arange(0,55,5)
f

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
#array with specific line space
g= np.linspace(3,33,num=10)
g

array([ 3.        ,  6.33333333,  9.66666667, 13.        , 16.33333333,
       19.66666667, 23.        , 26.33333333, 29.66666667, 33.        ])

In [25]:
#specify data type to int
h = np.ones(5,dtype=np.int64)
h

array([1, 1, 1, 1, 1], dtype=int64)

In [26]:
#specify data type to float
i = np.ones(5,dtype=np.float64)
i

array([1., 1., 1., 1., 1.])

###   Array Functions


In [27]:
j= np.array([10,12,15,4.,5.,8.,79,66,55])
j

array([10., 12., 15.,  4.,  5.,  8., 79., 66., 55.])

In [28]:
j.sort()
j

array([ 4.,  5.,  8., 10., 12., 15., 55., 66., 79.])

In [29]:
k=np.arange(9)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
#conctenate j and k
l=np.concatenate((j,k))
l

array([ 4.,  5.,  8., 10., 12., 15., 55., 66., 79.,  0.,  1.,  2.,  3.,
        4.,  5.,  6.,  7.,  8.])

In [31]:
#sorting again
l.sort()
l

array([ 0.,  1.,  2.,  3.,  4.,  4.,  5.,  5.,  6.,  7.,  8.,  8., 10.,
       12., 15., 55., 66., 79.])

### 2-D Arrays

In [32]:
a= np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [33]:
b=np.array([[6,7,8,9,10],[10,9,8,7,6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [34]:
# Concatenate 2D-arrays if dimensions are same
c=np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [35]:
# Concatenate 2D-arrays if dimensions are same
c=np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [36]:
# Concatenate 2D-arrays if dimensions are not same
x=np.array([[3,4,5],[1,2,3]])
x
y=np.array([[6,7,8]])
y
z=np.concatenate((x,y), axis=0)
z

array([[3, 4, 5],
       [1, 2, 3],
       [6, 7, 8]])

In [37]:
#finding dimension number
# v=np.ndim(z)
# v
#or
z.ndim

2

In [38]:
b=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
b.ndim

2

###  3-D Arrays or *Tensor*

In [40]:
#Tensor
a=np.array([[[1,2,3],
           [4,5,6]],
            
          [[7,8,9],
          [10,11,12]],
            
          [[13,14,15],
          [16,17,18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [41]:
a.ndim

3

In [42]:
type(a)

numpy.ndarray

In [43]:
#size of array(number of elements)
a.size

18

In [44]:
#shape of array
a.shape

(3, 2, 3)

In [45]:
# a new tensor
#Tensor
x=np.array([[[1,2,3,2],
           [4,5,6,2]],
            
          [[7,8,9,2],
          [10,11,12,2]],
            
          [[13,14,15,2],
          [16,17,18,2]]])
x

array([[[ 1,  2,  3,  2],
        [ 4,  5,  6,  2]],

       [[ 7,  8,  9,  2],
        [10, 11, 12,  2]],

       [[13, 14, 15,  2],
        [16, 17, 18,  2]]])

In [46]:
# finding shape in format((dimensions),(rows),(columns))
x.shape

(3, 2, 4)

In [47]:
#reshaping an array after its formation
d= np.arange(9)#reshape in multiply order i.e 3*3=9
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
#reshape
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
#Reshape array by another way
np.reshape(d, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [50]:
#convert 1D array into 2D
a=np.arange(9)
a
a.shape

(9,)

In [51]:
# rows 2d conversion
b=a[np.newaxis,:]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [52]:
b.shape

(1, 9)

In [53]:
# making columns from rows
c=a[:,np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [54]:
c.shape

(9, 1)

In [55]:
#indexing:slicing
c[3:7]

array([[3],
       [4],
       [5],
       [6]])

In [56]:
# Multiplying 6 with all elements
c*6

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30],
       [36],
       [42],
       [48]])

In [57]:
# Addition with 6
c+6

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [58]:
# finding sum of array
c.sum()

36

In [59]:
#finding mean of array
c.mean()

4.0